export const reduxConstants = {
    SHOW_DRAWER: 'SHOW_DRAWER',
    HIDE_DRAWER: 'HIDE_DRAWER',
    SET_BARISTA_ACTIVE_PRODUCT: 'SET_BARISTA_ACTIVE_PRODUCT',
    SET_ORDERS: 'SET_ORDERS',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR'
}