export const reduxConstants = {
    SHOW_DRAWER: 'SHOW_DRAWER',
    HIDE_DRAWER: 'HIDE_DRAWER',
    SET_BARISTA_ACTIVE_PRODUCT: 'SET_BARISTA_ACTIVE_PRODUCT',
    SET_ORDERS: 'SET_ORDERS',
    SET_LAST_ORDER_ID: 'SET_LAST_ORDER_ID',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    HIDE_SNACKBAR: 'HIDE_SNACKBAR',

}